# SPDX-License-Identifier: GPL-2.0-or-later
PKG_VERSION="464b3e7bf45bb300e190339977abba36c8078e1f"
PKG_SITE="https://github.com/beebono/linux-mainline-sprd"
PKG_URL="${PKG_SITE}.git"
PKG_GIT_CLONE_BRANCH="rg-rotate"
PKG_NEED_UNPACK+=" ${PROJECT_DIR}/${PROJECT}/devices/T618/firmware-manifest.json"
PKG_NEED_UNPACK+=" ${PROJECT_DIR}/${PROJECT}/devices/T618/packages/t618-kernel-integration"
PKG_SHA256=""
PKG_PATCH_DIRS=""
PKG_BUILD_PERF="no"
