# SPDX-License-Identifier: GPL-2.0-or-later
# kernel.org Linux 7.1.2 + the rg-rotate ums512 support series (patches/linux/rg-rotate).
PKG_VERSION="7.1.2"
PKG_SITE="https://www.kernel.org"
PKG_URL="https://www.kernel.org/pub/linux/kernel/v7.x/linux-${PKG_VERSION}.tar.xz"
PKG_SHA256="37198c93727be247c9fb5309bb86cd5e496c61e5322cd8c4eca9476bb0b5883f"
PKG_NEED_UNPACK+=" ${PROJECT_DIR}/${PROJECT}/devices/T618/firmware-manifest.json"
PKG_NEED_UNPACK+=" ${PROJECT_DIR}/${PROJECT}/devices/T618/packages/t618-kernel-integration"
PKG_PATCH_DIRS="rg-rotate"
PKG_BUILD_PERF="no"
